runmode: debug                # 开发模式, debug, release, test
addr: :8082                   # HTTP绑定端口
name: kronos                  # API Server的名字
url: http://127.0.0.1:8082   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10            # pingServer函数try的次数
jwt_secret:
loc: Asia/Shanghai
tls:
  addr: :8081
  cert: cert/server.crt
  key: cert/server.key
locus:
  path: storage/logs/
  file: access.log
db:
  type: mysql
  name: kronos
  addr: 127.0.0.1:3306
  charset: utf8mb4
  username: root
  password: root
